services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_rental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  # flask-app:
  #   build: .
  #   volumes:
  #     - .:/app
  #   environment:
  #     - FLASK_APP=run.py
  #     - FLASK_ENV=development
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db

volumes:
  postgres_data:
    driver: local