"""Ajout des champs image_voiture et gestion des modèles

Revision ID: 230882cad567
Revises: 015e1e49a705
Create Date: 2025-03-02 20:55:42.262157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230882cad567'
down_revision = '015e1e49a705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('voiture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etat', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voiture', schema=None) as batch_op:
        batch_op.drop_column('etat')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
